services:
  mysql:
    image: mysql:8.4.0
    container_name: mysql_container 
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: lime
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: indentity_service
    volumes:
      - ./mysql/data:/var/lib/mysql
